apiVersion: v1
kind: Namespace
metadata:
  name: k2a-mcp-servers
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
