# =============================================================================
# kmcp Helm Values - v0.2.2
# =============================================================================
#
# Configuracion de produccion para kmcp controller
# Documentacion: https://github.com/kagent-dev/kmcp
#
# kmcp gestiona MCP servers con transporte stdio en Kubernetes.
#
# =============================================================================

# ============================================
# NAMESPACE CONFIGURATION
# ============================================
namespaceOverride: "kmcp-system"

# ============================================
# IMAGE CONFIGURATION
# ============================================
image:
  repository: ghcr.io/kagent-dev/kmcp/controller
  pullPolicy: IfNotPresent
  # tag: ""  # Use chart's appVersion by default

# Image pull secrets for private registries
imagePullSecrets: []

# ============================================
# CONTROLLER CONFIGURATION
# ============================================
controller:
  # Number of replicas (use 1 with leader election)
  replicaCount: 1

  # Leader Election for HA
  leaderElection:
    enabled: true

  # Health Probes
  healthProbe:
    bindAddress: ":8081"
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10

  # Metrics Configuration
  metrics:
    enabled: true
    bindAddress: ":8443"
    secureServing: true

  # Environment variables
  env: []
  # - name: LOG_LEVEL
  #   value: "debug"

# ============================================
# POD SECURITY CONTEXT
# ============================================
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# ============================================
# CONTAINER SECURITY CONTEXT
# ============================================
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
  readOnlyRootFilesystem: true
  runAsNonRoot: true

# ============================================
# RESOURCES
# ============================================
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# ============================================
# SERVICE ACCOUNT
# ============================================
serviceAccount:
  create: true
  annotations: {}
  # For AWS IRSA:
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/kmcp-role"
  name: ""

# ============================================
# RBAC
# ============================================
rbac:
  create: true

# ============================================
# SERVICE (Metrics)
# ============================================
service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

# ============================================
# POD ANNOTATIONS
# ============================================
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8443"
  prometheus.io/scheme: "https"

# ============================================
# SCHEDULING
# ============================================
nodeSelector: {}
# kubernetes.io/os: linux

tolerations: []
# - key: "node-role.kubernetes.io/control-plane"
#   operator: "Exists"
#   effect: "NoSchedule"

affinity: {}
# podAntiAffinity:
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 100
#     podAffinityTerm:
#       labelSelector:
#         matchLabels:
#           app.kubernetes.io/name: kmcp
#       topologyKey: kubernetes.io/hostname
