# =============================================================================
# kagent Helm Values - v0.7.6
# =============================================================================
#
# Minimal configuration for kagent operator
# Uses chart defaults where possible
#
# PREREQUISITO: Crear el secret de OpenAI antes de desplegar
#   kubectl create namespace kagent
#   kubectl create secret generic kagent-openai-secret \
#     --namespace kagent \
#     --from-literal=api-key="sk-..."
#
# =============================================================================

# Registry override
registry: "ghcr.io"

# Database
database:
  type: sqlite

# Controller
controller:
  replicas: 1
  loglevel: "info"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# UI
ui:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Tools server
tools:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Disable pre-configured agents (we use our own k2a-agent)
agents:
  k8sAgent:
    enabled: false
  helmAgent:
    enabled: false
  istioAgent:
    enabled: false
  argoAgent:
    enabled: false
  prometheusAgent:
    enabled: false
  grafanaAgent:
    enabled: false
  ciliumAgent:
    enabled: false
  crossplaneAgent:
    enabled: false
  awsAgent:
    enabled: false

# Service Account
serviceAccount:
  create: true

# RBAC
rbac:
  create: true
