# =============================================================================
# kagent Helm Values - v0.7.6
# =============================================================================
#
# Minimal configuration for kagent operator
# Uses chart defaults where possible
#
# PREREQUISITO: Crear el secret de OpenAI antes de desplegar
#   kubectl create namespace kagent
#   kubectl create secret generic kagent-openai-secret \
#     --namespace kagent \
#     --from-literal=api-key="sk-..."
#
# =============================================================================

# Registry override (chart default is cr.kagent.dev)
registry: "ghcr.io"

# Database
database:
  type: sqlite

# Controller
controller:
  replicas: 1
  loglevel: "info"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

# UI
ui:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    ports:
      port: 8080
      targetPort: 8080

# LLM Providers - usar OpenAI con el secret existente
providers:
  default: openAI
  openAI:
    provider: OpenAI
    model: "gpt-4.1-mini"
    apiKeySecretRef: kagent-openai-secret
    apiKeySecretKey: api-key

# Disable KMCP subchart (we install kmcp separately)
kmcp:
  enabled: false

# Built-in tools server
kagent-tools:
  fullnameOverride: kagent-tools
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# Disable pre-configured agents (we use our own k2a-agent)
agents:
  k8s-agent:
    enabled: false
  kgateway-agent:
    enabled: false
  istio-agent:
    enabled: false
  promql-agent:
    enabled: false
  observability-agent:
    enabled: false
  argo-rollouts-agent:
    enabled: false
  helm-agent:
    enabled: false
  cilium-policy-agent:
    enabled: false
  cilium-manager-agent:
    enabled: false
  cilium-debug-agent:
    enabled: false

# MCP Tools (grafana-mcp, querydoc)
tools:
  grafana-mcp:
    enabled: false
  querydoc:
    enabled: false

# Disable grafana-mcp since we don't have Grafana
grafana-mcp:
  grafana:
    url: "grafana.kagent:3000/api"
    apiKey: "-"

# Disable querydoc
querydoc:
  replicas: 0

# =============================================================================
# Observability - OpenTelemetry Tracing
# =============================================================================
# Para ver trazas, desplegar Jaeger en el cluster:
#   kubectl create ns jaeger
#   kubectl apply -n jaeger -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/main/examples/simplest.yaml
#
# O usar el operador de Jaeger de OpenShift:
#   oc apply -f - <<EOF
#   apiVersion: jaegertracing.io/v1
#   kind: Jaeger
#   metadata:
#     name: jaeger
#     namespace: kagent
#   spec:
#     strategy: allInOne
#   EOF
otel:
  tracing:
    enabled: true
    exporter:
      otlp:
        # Jaeger collector endpoint (OTLP gRPC)
        # Jaeger desplegado en namespace k2a
        endpoint: http://jaeger-collector.k2a.svc.cluster.local:4317
  logging:
    enabled: false
