# =============================================================================
# K2A Production Values
# =============================================================================
#
# Este archivo contiene la configuracion de produccion para:
#   - MCP Servers (Quarkus Native: Prometheus, AlertManager, Red Hat Cases, Sessionize)
#   - K2A Agent (Agente de IA)
#
# ARQUITECTURA:
#   - Namespace 'k2a': Toda la aplicacion (Agent + MCP Servers)
#   - Namespace 'kagent': Solo el operador kagent (controller, ui, tools)
#
# PREREQUISITO: Crear los secrets antes de desplegar
#   kubectl create namespace k2a
#   kubectl create secret generic kagent-openai \
#     --namespace k2a \
#     --from-literal=OPENAI_API_KEY="sk-..."
#
# =============================================================================

# =============================================================================
# SECCION 1: MCP SERVERS (chart: kmcp-servers) - Quarkus Native
# =============================================================================

# Namespace unificado para toda la aplicacion K2A
global:
  namespace: k2a

# =============================================================================
# RBAC Configuration for OpenShift Monitoring Access
# =============================================================================
# The built-in cluster-monitoring-view ClusterRole doesn't include alertmanagers/api
# We create a custom ClusterRole with proper permissions for both Prometheus and AlertManager
rbac:
  create: true
  serviceAccount:
    name: kmcp-servers
    annotations: {}
  # Custom ClusterRole for OpenShift Monitoring API access
  # Creates: ClusterRole k2a-monitoring-api-access + ClusterRoleBinding
  monitoringApiAccess:
    create: true
  # Optional: Additional binding to cluster-monitoring-view (disabled by default)
  clusterRoleBinding:
    create: false
    clusterRole: cluster-monitoring-view

servers:
  # ------------------------------------------
  # Prometheus MCP Server (Quarkus Native)
  # ------------------------------------------
  # NOTA: Usando HTTP transport directo (sin Transport Adapter)
  # Quarkus expone HTTP/SSE nativo en /mcp endpoint
  prometheus:
    enabled: true
    name: prometheus-mcp
    description: "MCP Server para consultas PromQL a Prometheus/Thanos (Quarkus Native)"
    transportType: http
    image:
      repository: ghcr.io/jeanlopezxyz/mcp-prometheus
      tag: "1.0.8"
    port: 9081  # Puerto HTTP nativo de Quarkus
    httpTransport:
      targetPort: 9081
      path: /mcp  # Streamable HTTP endpoint
    env:
      PROMETHEUS_URL: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
      # HTTP mode - stdio disabled
      QUARKUS_MCP_SERVER_STDIO_ENABLED: "false"
      QUARKUS_HTTP_PORT: "9081"
      QUARKUS_HTTP_HOST: "0.0.0.0"
      # Trust OpenShift internal SSL certificates
      QUARKUS_TLS_TRUST_ALL: "true"
      # Session timeout (5 minutes) to prevent premature session termination
      QUARKUS_MCP_SERVER_HTTP_SESSION_TIMEOUT: "300"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  # ------------------------------------------
  # AlertManager MCP Server (Quarkus Native)
  # ------------------------------------------
  # NOTA: Usando HTTP transport directo (sin Transport Adapter)
  # Quarkus expone HTTP/SSE nativo en /mcp endpoint
  alertmanager:
    enabled: true
    name: alertmanager-mcp
    description: "MCP Server para AlertManager (Quarkus Native)"
    transportType: http
    image:
      repository: ghcr.io/jeanlopezxyz/mcp-alertmanager
      tag: "1.0.13"
    port: 9082  # Puerto HTTP nativo de Quarkus
    httpTransport:
      targetPort: 9082
      path: /mcp  # Streamable HTTP endpoint
    env:
      ALERTMANAGER_URL: "https://alertmanager-main.openshift-monitoring.svc.cluster.local:9094"
      # HTTP mode - stdio disabled
      QUARKUS_MCP_SERVER_STDIO_ENABLED: "false"
      QUARKUS_HTTP_PORT: "9082"
      QUARKUS_HTTP_HOST: "0.0.0.0"
      # Trust OpenShift internal SSL certificates
      QUARKUS_TLS_TRUST_ALL: "true"
      # Session timeout (5 minutes) to prevent premature session termination
      QUARKUS_MCP_SERVER_HTTP_SESSION_TIMEOUT: "300"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  # ------------------------------------------
  # Red Hat Cases MCP Server (Quarkus Native)
  # ------------------------------------------
  # NOTA: Usando HTTP transport directo (sin Transport Adapter)
  # Quarkus expone HTTP/SSE nativo en /mcp endpoint
  redhatCases:
    enabled: true
    name: redhat-cases-mcp
    description: "MCP Server para Red Hat KB y casos de soporte (Quarkus Native)"
    transportType: http
    image:
      repository: ghcr.io/jeanlopezxyz/mcp-redhat-cases
      tag: "latest"
    port: 9083  # Puerto HTTP nativo de Quarkus
    httpTransport:
      targetPort: 9083
      path: /mcp  # Streamable HTTP endpoint
    env:
      # HTTP mode - stdio disabled
      QUARKUS_MCP_SERVER_STDIO_ENABLED: "false"
      QUARKUS_HTTP_PORT: "9083"
      QUARKUS_HTTP_HOST: "0.0.0.0"
      # Session timeout (5 minutes) to prevent premature session termination
      QUARKUS_MCP_SERVER_HTTP_SESSION_TIMEOUT: "300"
    secretRefs:
      - redhat-cases-mcp-secrets
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  # ------------------------------------------
  # Sessionize MCP Server (Quarkus Native)
  # ------------------------------------------
  # NOTA: Usando HTTP transport directo (sin Transport Adapter)
  # Quarkus expone HTTP/SSE nativo en /mcp endpoint
  sessionize:
    enabled: true
    name: sessionize-mcp
    description: "MCP Server para Sessionize - conferencias y eventos (Quarkus Native)"
    transportType: http
    image:
      repository: ghcr.io/jeanlopezxyz/mcp-sessionize
      tag: "1.0.2"
    port: 9084  # Puerto HTTP nativo de Quarkus
    httpTransport:
      targetPort: 9084
      path: /mcp  # Streamable HTTP endpoint
    env:
      # HTTP mode - stdio disabled
      QUARKUS_MCP_SERVER_STDIO_ENABLED: "false"
      QUARKUS_HTTP_PORT: "9084"
      QUARKUS_HTTP_HOST: "0.0.0.0"
      # Session timeout (5 minutes) to prevent premature session termination
      QUARKUS_MCP_SERVER_HTTP_SESSION_TIMEOUT: "300"
      # SESSIONIZE_EVENT_ID: ""  # Configurar via secret o tool parameter
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi

  # ------------------------------------------
  # Kubernetes MCP Server (Go Native)
  # ------------------------------------------
  # NOTA: Usando HTTP transport directo
  # Go nativo expone HTTP en /mcp endpoint con /healthz health check
  kubernetes:
    enabled: true
    name: kubernetes-mcp
    description: "MCP Server para gestion de Kubernetes/OpenShift (Go Native)"
    transportType: http
    image:
      repository: quay.io/containers/kubernetes_mcp_server
      tag: "latest"
    port: 8080  # Puerto HTTP nativo de Go
    httpTransport:
      targetPort: 8080
      path: /mcp
    env:
      # Enable OpenShift specific features
      OPENSHIFT: "true"
    # ServiceAccount needs cluster-admin or appropriate RBAC
    serviceAccount:
      create: true
      name: kubernetes-mcp
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    # Custom health check path for Go server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 30
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10

# =============================================================================
# SECCION 2: K2A AGENT (chart: kagent-app)
# =============================================================================

# ModelConfig - Configuracion del modelo LLM principal
# gpt-4o-mini: 15x m치s econ칩mico que gpt-4o, r치pido, 128K contexto
modelConfig:
  create: true
  name: k2a-openai-config
  provider: OpenAI
  model: gpt-4o-mini
  secretRef:
    name: kagent-openai
    key: OPENAI_API_KEY

# Modelos adicionales
additionalModelConfigs:
  # DeepSeek - Modelo econ칩mico y potente
  # deepseek-chat: Modelo general (DeepSeek-V3.2)
  # deepseek-reasoner: Razonamiento avanzado con chain-of-thought
  deepseek:
    create: true
    name: k2a-deepseek-config
    provider: OpenAI  # DeepSeek usa API compatible con OpenAI
    model: deepseek-chat
    secretRef:
      name: kagent-deepseek
      key: DEEPSEEK_API_KEY
    openAI:
      baseUrl: "https://api.deepseek.com"
      temperature: "0.7"
      maxTokens: 4096

# Agent configuration
agent:
  name: k2a-enterprise-monitoring
  namespace: k2a  # Mismo namespace que MCP servers para usar MCPServer (kmcp)
  modelConfig: k2a-openai-config  # Opciones: k2a-openai-config, k2a-deepseek-config
  # Use ConfigMap for systemMessage (scalable option)
  systemMessageConfigMap:
    enabled: true
    create: true
    name: k2a-system-prompt
    key: system-prompt
  systemMessage: |
    You are K2A, an AI agent for Kubernetes enterprise monitoring.

    Available Tools by Category:

    ALERTMANAGER (for alerts, silences, notifications):
    - getAlerts: Get current firing and silenced alerts
    - getAlertGroups: Get alerts organized by routing groups
    - getSilences: List active and expired silences
    - createSilence: Create silence for maintenance
    - deleteSilence: Remove a silence
    - getReceivers: List notification receivers
    - getAlertmanagerStatus: Check AlertManager health

    PROMETHEUS (for metrics and monitoring):
    - query: Execute instant PromQL query
    - queryRange: Execute range query for time series
    - getRules: Get alerting and recording rules
    - getTargets: Get scrape target status
    - getPrometheusStatus: Check Prometheus health

    KUBERNETES (for cluster management):
    - configuration_view: View current kubeconfig context
    - configuration_set_namespace: Set default namespace
    - pods_list: List pods in namespace
    - pods_get: Get pod details
    - pods_log: Get pod logs
    - pods_run: Run a new pod
    - pods_exec: Execute command in pod
    - pods_delete: Delete a pod
    - resources_list: List any Kubernetes resources
    - resources_get: Get resource details
    - resources_create_or_update: Create or update resources
    - resources_delete: Delete resources
    - events_list: List cluster events
    - helm_install: Install Helm chart
    - helm_uninstall: Uninstall Helm release
    - helm_list: List Helm releases
    - helm_status: Get Helm release status
    - helm_rollback: Rollback Helm release

    RED HAT SUPPORT (for KB and cases):
    - searchKnowledgeBase: Search Red Hat KB articles
    - getSolution: Get full KB article content
    - createCase: Create support case
    - getCase: Get case details
    - searchCases: List and filter cases
    - addComment: Add comment to case

    Tool Selection Rules:
    - For ALERTS: Use getAlerts or getAlertGroups
    - For METRICS: Use query or queryRange
    - For KUBERNETES RESOURCES: Use pods_list, resources_list, resources_get
    - For POD TROUBLESHOOTING: Use pods_log, pods_exec
    - For HELM: Use helm_list, helm_status
    - For RED HAT KB: Use searchKnowledgeBase
    - For SUPPORT CASES: Use searchCases, createCase, getCase

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# MCPServer references (kmcp) - Agent y MCP servers en mismo namespace
# El Agent referencia directamente los MCPServer CRDs de kmcp (sin URLs)
# Esto es posible porque todo esta en namespace 'k2a'
mcpServers:
  prometheus:
    enabled: true
    name: prometheus-mcp  # Debe coincidir con servers.prometheus.name
    tools:
      - query
      - queryRange
      - getRules
      - getTargets
      - getPrometheusStatus

  alertmanager:
    enabled: true
    name: alertmanager-mcp  # Debe coincidir con servers.alertmanager.name
    tools:
      - getAlerts
      - getAlertGroups
      - getSilences
      - createSilence
      - deleteSilence
      - getReceivers
      - getAlertmanagerStatus

  redhatCases:
    enabled: true  # Re-enabled with latest image
    name: redhat-cases-mcp  # Debe coincidir con servers.redhatCases.name
    tools:
      - searchKnowledgeBase
      - getSolution
      - createCase
      - getCase
      - addComment
      - searchCases
      - updateCase
      - getAccountInfo
      - getEntitlements
      - getStatistics
      - listProducts
      - listVersions

  sessionize:
    enabled: false  # Temporarily disabled
    name: sessionize-mcp  # Debe coincidir con servers.sessionize.name
    tools:
      - getSpeakers
      - findSpeaker
      - getSessionsBySpeaker
      - getSessions
      - findSession
      - getSchedule

  kubernetes:
    enabled: true
    name: kubernetes-mcp  # Debe coincidir con servers.kubernetes.name
    tools:
      # Core Kubernetes tools
      - configuration_view
      - configuration_set_namespace
      - pods_list
      - pods_get
      - pods_log
      - pods_run
      - pods_exec
      - pods_delete
      - resources_list
      - resources_get
      - resources_create_or_update
      - resources_delete
      - events_list
      # Helm tools
      - helm_install
      - helm_uninstall
      - helm_list
      - helm_status
      - helm_rollback

# A2A Skills
a2aSkills:
  - id: alert-monitoring
    name: Alert Monitoring
    description: Monitor and analyze alerts from Prometheus and AlertManager
    examples:
      - What alerts are currently firing?
      - Show me critical alerts
    tags:
      - alerts
      - monitoring
    inputModes:
      - text
    outputModes:
      - text

  - id: metrics-analysis
    name: Metrics Analysis
    description: Query and analyze Prometheus metrics
    examples:
      - What is the CPU usage?
      - Show memory usage
    tags:
      - metrics
      - prometheus
    inputModes:
      - text
    outputModes:
      - text

  - id: redhat-support
    name: Red Hat Support
    description: Search Red Hat KB and manage support cases
    examples:
      - Search for OOMKilled errors
      - Create a support case
    tags:
      - redhat
      - kb
      - support
    inputModes:
      - text
    outputModes:
      - text

  - id: conference-info
    name: Conference Information
    description: Get speakers, sessions and schedule from Sessionize events
    examples:
      - Who are the speakers at the conference?
      - Find sessions about Kubernetes
      - What's the schedule for today?
    tags:
      - conference
      - sessionize
      - speakers
    inputModes:
      - text
    outputModes:
      - text

  - id: kubernetes-management
    name: Kubernetes Management
    description: Manage Kubernetes/OpenShift cluster resources, pods, deployments, and Helm releases
    examples:
      - List pods in namespace default
      - Get logs from pod nginx
      - Show deployment status
      - List Helm releases
    tags:
      - kubernetes
      - openshift
      - pods
      - helm
    inputModes:
      - text
    outputModes:
      - text

# =============================================================================
# SECCION 3: CONFIGURACION COMPARTIDA
# =============================================================================

networkPolicy:
  enabled: false  # Disabled - was blocking traffic from kagent namespace

monitoring:
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: true

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false
