# Production values for MCP Servers
# Environment: OpenShift with internal monitoring

servers:
  prometheus:
    enabled: true
    name: prometheus-mcp
    replicas: 1
    image:
      repository: k2a-mcp-servers/prometheus-mcp
      tag: latest
      pullPolicy: Always
    port: 8000
    command: ["python", "-m", "prometheus_mcp"]
    args: ["--transport", "streamable-http", "--port", "8000"]
    config:
      PROMETHEUS_URL: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
      PROMETHEUS_VERIFY_SSL: "false"
      LOG_LEVEL: "info"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    probes:
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 60
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 30
    imageStream:
      enabled: true
    build:
      enabled: true
      gitUri: https://github.com/jeanlopezxyz/k2a-enterprise-monitoring.git
      gitRef: main
      contextDir: src/prometheus-mcp

  alertmanager:
    enabled: true
    name: alertmanager-mcp
    replicas: 1
    image:
      repository: k2a-mcp-servers/alertmanager-mcp
      tag: latest
      pullPolicy: Always
    port: 8000
    command: ["python", "-m", "alertmanager_mcp"]
    args: ["--transport", "streamable-http", "--port", "8000"]
    config:
      ALERTMANAGER_URL: "https://alertmanager-main.openshift-monitoring.svc.cluster.local:9094"
      ALERTMANAGER_VERIFY_SSL: "false"
      LOG_LEVEL: "info"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    probes:
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 60
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 30
    imageStream:
      enabled: true
    build:
      enabled: true
      gitUri: https://github.com/jeanlopezxyz/k2a-enterprise-monitoring.git
      gitRef: main
      contextDir: src/alertmanager-mcp

  redhatCases:
    enabled: true
    name: redhat-cases-mcp
    replicas: 1
    image:
      repository: k2a-mcp-servers/redhat-cases-mcp
      tag: latest
      pullPolicy: Always
    port: 8000
    command: ["python", "-m", "redhat_cases_mcp"]
    args: ["--transport", "streamable-http", "--port", "8000"]
    config:
      LOG_LEVEL: "info"
    secrets:
      REDHAT_API_OFFLINE_TOKEN: ""  # Set via external secret or sealed-secrets
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    probes:
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 60
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 30
    imageStream:
      enabled: true
    build:
      enabled: true
      gitUri: https://github.com/jeanlopezxyz/k2a-enterprise-monitoring.git
      gitRef: main
      contextDir: src/redhat-cases-mcp
