# RemoteMCPServer resources for kagent to connect to our MCP servers
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: prometheus-mcp-server
  namespace: kagent
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
spec:
  description: "Prometheus MCP Server for querying metrics"
  protocol: STREAMABLE_HTTP
  terminateOnClose: true
  timeout: 30s
  url: "http://prometheus-mcp.k2a-mcp-servers.svc.cluster.local:8000/mcp"
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: alertmanager-mcp-server
  namespace: kagent
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
spec:
  description: "AlertManager MCP Server for managing alerts"
  protocol: STREAMABLE_HTTP
  terminateOnClose: true
  timeout: 30s
  url: "http://alertmanager-mcp.k2a-mcp-servers.svc.cluster.local:8000/mcp"
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: redhat-cases-mcp-server
  namespace: kagent
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
spec:
  description: "Red Hat Cases MCP Server for KB and support cases"
  protocol: STREAMABLE_HTTP
  terminateOnClose: true
  timeout: 30s
  url: "http://redhat-cases-mcp.k2a-mcp-servers.svc.cluster.local:8000/mcp"
