apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k2a-agent
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k2a-enterprise-monitoring
  source:
    repoURL: 'https://github.com/jeanlopezxyz/k2a-enterprise-monitoring.git'
    targetRevision: main
    path: charts/k2a-agent
    helm:
      valueFiles:
        - values.yaml
        - ../../argocd/values/k2a-agent-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: kagent.dev
      kind: Agent
      jsonPointers:
        - /status
    - group: kagent.dev
      kind: RemoteMCPServer
      jsonPointers:
        - /status
