# Red Hat Cases MCP Server
apiVersion: v1
kind: ConfigMap
metadata:
  name: redhat-cases-mcp-config
  namespace: k2a-mcp-servers
  labels:
    app.kubernetes.io/name: redhat-cases-mcp
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
data:
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: redhat-cases-mcp-secrets
  namespace: k2a-mcp-servers
  labels:
    app.kubernetes.io/name: redhat-cases-mcp
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
type: Opaque
stringData:
  REDHAT_API_OFFLINE_TOKEN: ""  # Set via SealedSecret or external secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redhat-cases-mcp
  namespace: k2a-mcp-servers
  labels:
    app.kubernetes.io/name: redhat-cases-mcp
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
    app.kubernetes.io/component: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redhat-cases-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redhat-cases-mcp
        app.kubernetes.io/part-of: k2a-enterprise-monitoring
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redhat-cases-mcp
          image: image-registry.openshift-image-registry.svc:5000/k2a-mcp-servers/redhat-cases-mcp:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          command:
            - python
            - -m
            - redhat_cases_mcp
          args:
            - --transport
            - streamable-http
            - --port
            - "8000"
          envFrom:
            - configMapRef:
                name: redhat-cases-mcp-config
            - secretRef:
                name: redhat-cases-mcp-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redhat-cases-mcp
  namespace: k2a-mcp-servers
  labels:
    app.kubernetes.io/name: redhat-cases-mcp
    app.kubernetes.io/part-of: k2a-enterprise-monitoring
spec:
  selector:
    app.kubernetes.io/name: redhat-cases-mcp
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
